#!/bin/bash

# 快速解决方案：从手机提取当前APP的签名信息
# 注意：这个方法需要先从手机导出已安装的APK

echo "======================================"
echo "签名不一致问题 - 快速解决方案"
echo "======================================"
echo ""
echo "问题原因："
echo "  手机上的APP和新构建的APK使用了不同的签名密钥"
echo ""
echo "解决方法（3选1）："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法1: 卸载重装（最简单）⭐️"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. 先点击'导出车牌'保存数据"
echo "  2. 卸载手机上的旧版本"
echo "  3. 安装新版本APK"
echo "  4. 重新开启无障碍服务"
echo "  ⚠️  注意：无障碍服务需要重新授权"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法2: 生成固定签名（推荐长期使用）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  需要JDK环境，请选择以下方式之一："
echo ""
echo "  A. 使用Android Studio生成（最简单）"
echo "     1. 打开Android Studio"
echo "     2. 菜单：Build → Generate Signed Bundle / APK"
echo "     3. 选择 APK → Next"
echo "     4. 点击 'Create new...'"
echo "     5. 填写信息："
echo "        - Key store path: 项目目录/keystore/release.keystore"
echo "        - Password: yunduanban2025"
echo "        - Alias: yunduanban"
echo "        - Key password: yunduanban2025"
echo "        - Validity: 25年"
echo "        - Certificate:"
echo "          First and Last Name: YunDuanBan"
echo "          Organizational Unit: YUWEI"
echo "          Organization: Future Center"
echo "          City: Guangzhou"
echo "          State: Guangdong"
echo "          Country Code: CN"
echo "     6. 点击 OK 生成"
echo "     7. 运行：git add keystore/release.keystore"
echo "     8. 运行：git commit -m 'add release keystore'"
echo "     9. 运行：git push"
echo "    10. 卸载手机旧版，安装新版（仅需一次）"
echo "    11. 以后更新就能直接覆盖安装了！"
echo ""
echo "  B. 使用命令行生成（需要先安装JDK）"
echo "     1. 安装JDK: brew install openjdk@17"
echo "     2. 运行本脚本重新生成密钥"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法3: 使用旧版APK的签名（复杂，不推荐）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  需要从手机导出已安装的APK并提取签名信息"
echo "  操作复杂，不建议使用"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 建议："
echo "  - 开发阶段：使用'方法1'（卸载重装）"
echo "  - 生产使用：使用'方法2'（固定签名）"
echo ""
echo "详细说明请查看："
echo "  - keystore/generate-keystore.md"
echo "  - keystore/README.md"
echo ""
